apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-page-quarkus-producer-pipeline
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/davgordo/developer-charts
    targetRevision: HEAD
    path: quarkus-pipeline
    helm:
      values: |
        domain: davgordo
        system: bookinfo
        component: product-page-quarkus-producer
        deployment: jvm
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m